spring.application.name=order-service
server.port=8084

spring.datasource.url=jdbc:h2:mem:cartdb

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update


spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secrete=veryconfidentialsecretekeyveryconfidentialsecretekey123
